only_prod: &only_prod
  filters:
    branches:
      only:
        - master

version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Create infrastructure
          command: |
            aws cloudformation deploy \
              --template-file infra/infrastructure.yaml \
              --stack-name Stackkk \
              --capabilities CAPABILITY_IAM

  update-ansible-inventory:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Update ansible inventory
          command: |
            echo "[all]" > inventory.txt
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
              --filters "Name=tag:Project,Values=ansible-playground" --output text >> inventory.txt
      - save_cache:
          key: inventory
          paths:
            - inventory.txt

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - af:bc:39:aa:be:fa:c3:25:32:fb:f5:10:4e:75:28:d0
      - restore_cache:
          key: inventory
          paths:
            - inventory.txt
      - run:
          name: Install Ansible
          command: |
            pip install ansible
      - run:
          name: Configure Infrastructure
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

workflows:
  default:
    jobs:
      - create-infrastructure:
          <<: *only_prod
      - update-ansible-inventory:
          <<: *only_prod
          requires:
            - create-infrastructure
      - configure-infrastructure:
          <<: *only_prod
          requires:
            - update-ansible-inventory