---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: install nodejs, npm
  apt:
    update_cache: yes
    name: ["nodejs", "npm"]
    state: latest

- name: install pm2
  npm:
    name: pm2
    state: latest
    global: yes

- name: create ~/web directory
  file:
    path: /web
    state: directory

- name: copy index.js to ~/web
  copy:
    src: index.js
    dest: /web/index.js

- name: (re)start app
  shell: pm2 restart app || pm2 start /web/index.js --name "app" -f
...